services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: phonesensors
      POSTGRES_DB: sensor_data
    ports:
      - "5432:5432"
    volumes:
      - phone-sensors-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: y2wei@ucsd.edu
      PGADMIN_DEFAULT_PASSWORD: phonesensors
    ports:
      - "5050:80"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    command: ps-server

volumes:
  phone-sensors-db:
